# Generated by Django 4.1.4 on 2022-12-15 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Chat name')),
                ('dtcreate', models.DateTimeField(auto_now_add=True, verbose_name='Datetime chat')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='ava/avadefault.png', upload_to='ava/', verbose_name='Avatar')),
                ('online', models.BooleanField(default=False, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024, verbose_name='Message text')),
                ('dtcreate', models.DateTimeField(auto_now_add=True, verbose_name='Datetime message')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberauthor', to='chatback.member', verbose_name='Author message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatback.chatroom', verbose_name='In chat')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='guests',
            field=models.ManyToManyField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberowner', to='chatback.member', verbose_name='User-creater'), related_name='memberguest', to='chatback.member', verbose_name='Members of chat'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberowner', to='chatback.member', verbose_name='User-creater'),
        ),
    ]
