# Generated by Django 4.1.4 on 2023-01-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatback', '0002_alter_chatroom_guests_alter_member_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='ava/', verbose_name='Avatar'),
        ),
    ]
