# Generated by Django 4.1.4 on 2022-12-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatback', '0002_alter_chatroom_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='memberguest', to='chatback.member', verbose_name='Members of chat'),
        ),
    ]
