# Generated by Django 4.1.4 on 2022-12-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatback', '0003_alter_chatroom_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Online/offline'),
        ),
    ]
